### ISSUE TITLE
opening the main file in dist problem

### ISSUE THREAD

**Issue by jimmybennet** [Vczz0/Cerberos-C2#14]
after trying to open the main file in dist to see if everything is working and when i ran main.exe i get 
(Traceback (most recent call last):
  File "main.py", line 21, in <module>
ModuleNotFoundError: No module named 'Crypto')

**Comment by vasileferentari** [comment]
You need to change from crypto to cryptodome and install pycryptodome

**Comment by vasileferentari** [comment]
tell me if it didnt work
